---
sudo: required
dist: trusty
language: python
python: "2.7"

install:
  - pip install ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../';  } >> ansible.cfg"

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
    # Run again to check for idempotence
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo 2>&1
    | tee output.file
  - >
    grep -q 'changed=0.*failed=0' output.file
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - oclint --version
