- name: Check for oclint
  stat: path=/usr/bin/oclint
  register: oclint_stat

- name: Download oclint
  get_url: >
    url={{ oclint_download_url }}
    dest=/tmp/oclint.tar.gz
  when: oclint_stat.stat.exists == False
  register: oclint_download

- name: Unpack oclint
  unarchive: >
    src=/tmp/oclint.tar.gz
    dest=/tmp
    copy=no
  when: oclint_download|success and not oclint_download|skipped
  register: oclint_unpack

- name: Install oclint
  shell: >
    mv /tmp/oclint-*/bin/* {{ oclint_install_dir }}/bin/ &&
    mv /tmp/oclint-*/lib/* {{ oclint_install_dir }}/lib/
  when: oclint_unpack|success and not oclint_unpack|skipped

- name: Cleanup
  shell: rm -r /tmp/oclint*
  when: oclint_download|success and not oclint_download|skipped
